FROM node:16.17

ARG NODE_ENV=development
ENV NODE_ENV=${NODE_ENV}

# Create the app directory
WORKDIR /home/node/coinsynch

# Copy package.json and package-lock.json to the container
COPY package*.json ./

# Install dependencies
RUN npm install -D

# Copy the rest of your application code
COPY . .

# Expose the port that the app will listen on
EXPOSE 3000

# Start the app
CMD ["npm", "start", "dev"]
